services:
  postgres-db:
    image: postgres:15
    container_name: nest-postgres-test
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postnest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Persistencia de datos local

networks:
  default:
    name: nest-network